### PR TITLE
feat: add return data to send multi sig

### PR DESCRIPTION
**Pull request by ryan-bitgo**
Addresses the following audit requirment

image

Tests failing with:

image

ticket: BG-43312

### CODE REVIEW

**Review by Omurshid — APPROVED** [review]
lgtm

**Comment by marktoda** [comment]
Who did the audit this time around?

**Comment by barathbitgo** [comment]
@ryan-bitgo is this needed?

**Comment by ryan-bitgo** [comment]
Well it doesn't work so probably not

**Pull request closed without merging**
