### PR TITLE
chore(eth-multisig-v4): add bera config

### PR DESCRIPTION
**Pull request by adarsh312**
Ticket: WIN-3295

### CODE REVIEW

**Review by dpkjnr — APPROVED** [review]

**Review by gianchandania — CHANGES_REQUESTED** [review]
I think this is not needed as we have to deploy v4 contracts, and these keys are used for v1

**Comment by dpkjnr** [comment]
> I think this is not needed as we have to deploy v4 contracts, and these keys are used for v1

we don't need to deploy v1 contracts? I think it might be needed for cross chain recovery

**Comment by gianchandania** [comment]
> > I think this is not needed as we have to deploy v4 contracts, and these keys are used for v1
> 
> we don't need to deploy v1 contracts? I think it might be needed for cross chain recovery

Ideally right now while developing berachain, we just deploy v4 contracts. v1 and v2 contracts are generally deployed later once cross chain work related to bera is taken up

**Comment by dpkjnr** [comment]
> > > I think this is not needed as we have to deploy v4 contracts, and these keys are used for v1
> > 
> > 
> > we don't need to deploy v1 contracts? I think it might be needed for cross chain recovery
> 
> Ideally right now while developing berachain, we just deploy v4 contracts. v1 and v2 contracts are generally deployed later once cross chain work related to bera is taken up

any idea why v1 script is getting executed even though tag is about v4? @gianchandania

**Pull request closed without merging**
